version: "3.9"

services:
  db:
    container_name: data_capstone
    image: postgres:12
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=data_capstone